# Generated by Django 5.2 on 2025-07-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_doctor_superadmin_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='superadmin_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
