# Generated by Django 5.2 on 2025-07-16 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_ipd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipd',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.doctor'),
        ),
        migrations.AlterField(
            model_name='ipd',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientsinfo'),
        ),
    ]
