# Generated by Django 5.2 on 2025-07-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_opd'),
    ]

    operations = [
        migrations.AddField(
            model_name='opd',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
