# Generated by Django 5.2 on 2025-07-18 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_opd_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opd',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='opd',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='opd',
            name='remarks',
        ),
    ]
