# Generated by Django 5.2 on 2025-07-18 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_remove_opd_diagnosis_remove_opd_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opd',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
