# Generated by Django 5.2 on 2025-07-18 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_opd_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opd',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
