# Generated by Django 5.2 on 2025-07-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_alter_opd_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alluser',
            name='restricted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
