# Generated by Django 5.2 on 2025-07-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_alluser_created_at_alluser_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='managePassowrd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
