# Generated by Django 5.2 on 2025-07-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_alluser_managepassowrd'),
    ]

    operations = [
        migrations.AddField(
            model_name='alluser',
            name='centerName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
