# Generated by Django 5.2 on 2025-07-23 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_alluser_centername'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superadmin_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
