# Generated by Django 5.2 on 2025-07-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_superadmin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='user',
        ),
    ]
